<h1>Страница не найдена!</h1>
<div class="row row-cols-1 row-cols-lg-2 align-items-lg-center">
    <div class="col">
        <img class="img-fluid" alt="Ошибка 404 – страница не найдена" src="/assets/404.svg" loading="lazy">
    </div>
    <div class="col">
        <h2 class="h2 mb-4">Ошибка 404</h2>
        <p class="fs-5 text-black mb-3">Что случилось?</p>
        <p class="mb-4">Вы попали на страницу, которой не существует.</p>
        <p class="fs-5 text-black mb-3">Почему это произошло?</p>
        <p class="mb-4">Обычно ошибка 404 возникает, когда страница была удалена, или вы ошиблись в адресе. Также возможно, что страница устарела, но сохранилась в закладках.</p>
        <p class="fs-5 text-black mb-3">Что делать?</p>
        <p class="mb-2">Рекомендуем вернуться <a href="/">на главную</a> и начать оттуда.</p>
    </div>
</div>