<h1>Упс, что-то пошло не так</h1>
<div class="row row-cols-1 row-cols-lg-2 align-items-lg-center">
    <div class="col">
        <img class="img-fluid" alt="Ошибка 500 – внутренняя ошибка сервера" src="/assets/500.svg" loading="lazy">
    </div>
    <div class="col">
        <h2 class="h2 mb-4">Ошибка 500</h2>
        <p class="fs-5 text-black mb-3">Что это значит?</p>
        <p class="mb-4">На сервере произошла внутренняя ошибка. Это может быть вызвано проблемой в коде или перегрузкой системы.</p>
        <p class="fs-5 text-black mb-3">Что можно сделать?</p>
        <p class="mb-2">Попробуйте <a href="/">вернуться на главную</a> или повторите попытку позже.</p>
    </div>
</div>