<div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
    <h1 class="display-3">Анализатор страниц</h1>
    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>

    <form action="<?= $router->urlFor('urls.store') ?>" method="post" class="row" required>
        <div class="col-8">
            <label for="url-input" class="visually-hidden">Url для проверки</label>
            <input
                type="text"
                id="url-input"
                name="url[name]"
                value="<?= isset($urlName) ? htmlspecialchars($urlName) : '' ?>"
                class="form-control form-control-lg <?= !empty($errors['url_name']) ? 'is-invalid' : '' ?>"
                placeholder="https://www.example.com"
            >
            <?php if (!empty($errors['url_name'])): ?>
                <div class="invalid-feedback"><?= htmlspecialchars($errors['url_name'][0]) ?></div>
            <?php endif; ?>
        </div>
        <div class="col-2">
            <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
        </div>
    </form>
</div>